### ISSUE TITLE
Performance when moving the window is terrible 

### ISSUE THREAD

**Issue by illegitimate-egg** [illixion/vscode-vibrancy-continued#10]
I literally cannot move my vscode windows with this theme applied.

**Comment by illixion** [comment]
Hi, sorry for the delay, could you please provide the following info:

- OS version
- VS Code version
- Current VS Code theme
- GPU or iGPU model (could be that it's not powerful enough for transparency effects?)

**Comment by jmgomez** [comment]
Same here. 
I personally know another person with the same problem.

Win 10
VSCode 1.7.02
The theme doesnt really matter as it happens with all of them.
3070 RTX

**Comment by illegitimate-egg** [comment]
> 

Windows 10
1.70.2
Dark+
Nvidia GEFORCE GTX 1650

**Comment by illixion** [comment]
I haven't been able to reproduce this issue, but it's likely caused by some other software. If someone can find any possible cause, let me know and I'll see if I can figure out a fix.

You can also use [GlassIt-VSC](https://marketplace.visualstudio.com/items?itemName=s-nlf-fh.glassit) to achieve transparency in the meantime.

**Comment by Get0457** [comment]
Hello!
I go and edit the file [VSCode Install Root]\resources\app\out\vscode-vibrancy-runtime-v6\index.js

I commented `win10refresh(window, 60);` and window moving is fine. I'm not sure if it will break the previous version of Windows. Tested on Windows 11
```javascript
	if (app.os === 'win10') {
		const bindings = require('./vibrancy.js');
		bindings.setVibrancy(window.getNativeWindowHandle().readInt32LE(0), 1, backgroundRGB.r, backgroundRGB.g, backgroundRGB.b, 0);
		const win10refresh = require('./win10refresh.js');
		// win10refresh(window, 60);

		window.webContents.once('dom-ready', () => {
			const currentURL = window.webContents.getURL();

			if (!(currentURL.includes('workbench.html') || currentURL.includes('workbench-monkey-patch.html'))) {
				return;
			}

			if (window.isMaximized()) {
				window.unmaximize();
				window.maximize();
			}
		});
	}
```
![image](https://user-images.githubusercontent.com/41405393/189067959-f919477f-76a5-4989-8841-8ccea70de1cd.png)

**Comment by illixion** [comment]
> Hello! I go and edit the file [VSCode Install Root]\resources\app\out\vscode-vibrancy-runtime-v6\index.js
> 
> I commented `win10refresh(window, 60);` and window moving is fine. I'm not sure if it will break the previous version of Windows. Tested on Windows 11
> 
> ```js
> 	if (app.os === 'win10') {
> 		const bindings = require('./vibrancy.js');
> 		bindings.setVibrancy(window.getNativeWindowHandle().readInt32LE(0), 1, backgroundRGB.r, backgroundRGB.g, backgroundRGB.b, 0);
> 		const win10refresh = require('./win10refresh.js');
> 		// win10refresh(window, 60);
> 
> 		window.webContents.once('dom-ready', () => {
> 			const currentURL = window.webContents.getURL();
> 
> 			if (!(currentURL.includes('workbench.html') || currentURL.includes('workbench-monkey-patch.html'))) {
> 				return;
> 			}
> 
> 			if (window.isMaximized()) {
> 				window.unmaximize();
> 				window.maximize();
> 			}
> 		});
> 	}
> ```
> 
> ![image](https://user-images.githubusercontent.com/41405393/189067959-f919477f-76a5-4989-8841-8ccea70de1cd.png)

Hi,

Thank you for finding a solution, would anyone in this thread like to test this on Windows 10? I'll implement this change if it works and doesn't break anything.

**Comment by shy-tan** [comment]
I faced the same issue on Windows 10. I updated my vscode to the latest version (1.71.1) and now its working fine.

**Comment by illixion** [comment]
> I faced the same issue on Windows 10. I updated my vscode to the latest version (1.71.1) and now its working fine.

Good to hear, thanks for reporting this. Could someone else from this thread update their VSCode and confirm that this issue is fully fixed and isn't an isolated case?

**Comment by illixion** [comment]
Closing as stale, feel free to comment if this issue is still present.

**Comment by iamvox** [comment]
Issue persists on 1.74 win10.

**Comment by iamvox** [comment]
The issue persists on vsc1.74 win10 165hz. Commenting out `win10refresh(window, 60);` didn't do much for me.
