### ISSUE TITLE
[Bug]: Not compatible with APC extension

### ISSUE THREAD

**Issue by sorae42** [illixion/vscode-vibrancy-continued#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This extension is not compatible with [APC](https://github.com/drcika/apc-extension), which I used for removing titlebar and stuff.

### Expected Behavior

Transparent windows along with my setup.

### Steps To Reproduce

Have APC installed and setup.

### Environment

```markdown
- OS: macOS 14
- VSCodium: 1.82.2
- Extension: 1.1.21
- Theme: Tokyo Night Storm
```

**Comment by illixion** [comment]
I don't provide support for third-party extensions, as many of them aren't programmed well or make sweeping changes to internal VSCode files that break any other extension that also wants to edit them. If you find any specific issues with Vibrancy Continued, please let me know.
