### ISSUE TITLE
Restore expected workbench.html

### ISSUE THREAD

**Issue by DaNubCoding** [illixion/vscode-vibrancy-continued#101]
I have installed another extension that seemed to have modified workbench.html, but now I have uninstalled the extension, Vibrancy still raises the same issue when I try to run any of its commands:

![image](https://github.com/illixion/vscode-vibrancy-continued/assets/75505891/a7cd9082-7109-4239-a72d-08002493dea6)

How would I fix this and get Vibrancy working again?

**Comment by illixion** [comment]
I should’ve clarified this, if the extension that modified it doesn’t have a rollback feature, then you’ll need to reinstall VSCode. It’s safe to do so and you won’t lose any changes.
