### ISSUE TITLE
[Bug]: Transparency effect doesn't apply to the integrated terminal in vsc

### ISSUE THREAD

**Issue by Pushan2005** [illixion/vscode-vibrancy-continued#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: Windows 11
- VSCode: 1.84.2
- Extension: 1.1.23
- Theme: Catppuccin Mocha with Monokai colour theme
```

**Comment by illixion** [comment]
Please check FAQ: https://github.com/illixion/vscode-vibrancy-continued#effect-doesnt-work-for-terminal
