### ISSUE TITLE
Uninstalling/disabling does not remove the effect

### ISSUE THREAD

**Issue by jackchealdang** [illixion/vscode-vibrancy-continued#11]
Hello, I've tried both disabling and uninstalling, just disabling, or just uninstalling and the effects do not go away after uninstallation.

**Comment by illixion** [comment]
Hi, could you please provide the following info:

- OS version
- VS Code version
- Current VS Code theme

Also, I assume you were using the Command Palette action "Disable Vibrancy" and not just disabling the extension through the Extensions menu? If so, did you notice any errors after running said action?

**Comment by illixion** [comment]
I've tested disabling the extension just now and it works as expected, please provide more info and I'll reopen the issue.

**Comment by vrlewf135** [comment]
> Hello, I've tried both disabling and uninstalling, just disabling, or just uninstalling and the effects do not go away after uninstallation.

metoo 
on macOS 13 using m1 MacBook pro
after uninstall or disable this extension , the effect won't go away

**Comment by illixion** [comment]
> > Hello, I've tried both disabling and uninstalling, just disabling, or just uninstalling and the effects do not go away after uninstallation.
> 
> metoo on macOS 13 using m1 MacBook pro after uninstall or disable this extension , the effect won't go away

Hi, just to make sure, you are using the Command Palette action "Disable Vibrancy" and not just disabling the extension through the Extensions menu?
