### ISSUE TITLE
[Bug]: not working in clean installation

### ISSUE THREAD

**Issue by du-cc** [illixion/vscode-vibrancy-continued#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

while being a CLEAN installation, it still doesn't work.

### Expected Behavior

acrylic effect

### Environment

```markdown
- OS:Windows 11 (rectify11)
- VSCode: 1.84.2
- Extension: vibrancy only
- Theme: dark+
```

### Anything else?

![image](https://github.com/illixion/vscode-vibrancy-continued/assets/67620716/2ac14cb5-1583-4bbf-95b0-61c36295253c)
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/67620716/7e87e378-ba85-4875-b0f8-4b8dd5f8eda5)
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/67620716/2d44d326-9900-4651-a3f8-82b9624c5c18)
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/67620716/5646636a-60e3-484b-bd3b-a08e64b6dfc3)
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/67620716/e9673962-1662-479e-a619-fc53244d1dc2)

**Comment by illixion** [comment]
Have you tried checking the FAQ in the description? It looks like you may have transparency effects disabled globally through Windows settings or a power saver mode.

**Comment by stefnotch** [comment]
I did the same thing (Windows 11 as well, latest version of VSCode), and Vibrancy didn't seem to do a thing.

I can confirm that it's not globally disabled. (I checked the Windows settings)

**Comment by stefnotch** [comment]
After some more testing, I set the opacity to 0.5. Now it very clearly seems to be doing its thing, so yay.

**Comment by illixion** [comment]
Odd, `-1` seems to be working fine on my end, so I'm not sure why it didn't work for you. I'll keep this in mind in case other people have a similar issue, thanks for the info!

**Comment by du-cc** [comment]
got it working but the effect is not that strong (but im sastified)

![image](https://github.com/illixion/vscode-vibrancy-continued/assets/67620716/f0444bbd-6f81-456f-a2bd-d28d157e5ebb)
