### ISSUE TITLE
[Bug]: Not working with VSCodium

### ISSUE THREAD

**Issue by j0of** [illixion/vscode-vibrancy-continued#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Extension is not working - background is still opaque.

### Expected Behavior

Transparent background.

### Steps To Reproduce

1. Open VSCodium as admin
2. Open Extensions menu (CTRL + Shift + X)
3. Install Vibrancy Continued (v1.1.24)
4. Restart VSCodium
5. Open command prompt (CTRL + Shift + P)
6. "Enable Vibrancy"
7. Restart again

### Environment

```markdown
- OS: Windows 11
- VSCode: VSCodium v1.84.2
- Extension: Vibrancy Continued v1.1.24
- Theme: Everforest Dark (attempted with recommended theme, failed)
```

### Anything else?

Also attempted with normal VSCode, succeeded.
![Screenshot 2023-12-05 224253](https://github.com/illixion/vscode-vibrancy-continued/assets/124946864/467a78d5-9fac-40cc-9ca6-b3f7bf7a59b5)

**Comment by illixion** [comment]
I don't have a Windows machine on hand at the moment, but I've just tried Vibrancy on macOS VSCodium and didn't encounter any issues. Were there any errors or messages from Vibrancy when setting it up? You can also try reinstalling VSCodium as it's possible that your installation is inconsistent.

**Comment by j0of** [comment]
Reinstalling VSCodium seemed to do the trick. Thanks!

**Comment by illixion** [comment]
Glad to hear!
