### ISSUE TITLE
[Bug]: mac v13 Full screen transparency failed

### ISSUE THREAD

**Issue by glimpde2** [illixion/vscode-vibrancy-continued#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

mac v13 Full screen transparency failed

### Expected Behavior

mac v13 Full screen transparency failed

### Steps To Reproduce

mac v13 Full screen transparency failed

### Environment

```markdown
mac v13 Full screen transparency failed
```

### Anything else?

mac v13 Full screen transparency failed

**Comment by illixion** [comment]
macOS doesn’t allow full-screen windows to have transparency as it creates a new “space” for full-screen windows, so the only option is to maximize instead. See #37 for more details.
