### ISSUE TITLE
[Bug]: Suddenly stopped working after hardware upgrade

### ISSUE THREAD

**Issue by JakeCH03** [illixion/vscode-vibrancy-continued#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I upgraded my system over christmas, was on an i5-9600k before and upgraded to a 7900X3D, I haven't changed anything else about my system, haven't updated windows, haven't updated drivers, was working perfectly before (after alot of trouble shooting haha) and now it just doesn't. Everything is correct in the settings as far as I can tell, no changes have been made anyways. Any reason why this might happened? 

### Environment

```markdown
- OS:
- VSCode:
- Extension:
- Theme:
```

**Comment by illixion** [comment]
Did you use the "Reload Vibrancy" action, and did you encounter any errors?

For further troubleshooting, please go to Help → About in VSCode and copy/paste the information from that section here. Also, please attach a screenshot of the main window, you can drag and drop the image into the comment here.

**Comment by JakeCH03** [comment]
I did, I went through reloading, reinstalling, triple checking the settings were still there. Everything is correct, it just suddenly stopped working

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621


![image](https://github.com/illixion/vscode-vibrancy-continued/assets/69173248/149866df-ed39-4171-8d14-7759374bac85)
 
 
 assuming this is the main window you wanted?

**Comment by JakeCH03** [comment]
Also, I did read something about acrylic not working properly, it was working previously and what I was using before, but setting that to auto still does nothing.

**Comment by illixion** [comment]
It looks like you're using "VSCode Animations", which I believe isn't compatible with Vibrancy as reported in #117, try reinstalling VSCode and enabling Vibrancy without VSCode Animations to confirm whether this is the case.

**Comment by JakeCH03** [comment]
Ah, that appeared to have worked, no idea why though I had the exact same extension installed before and it was running completely fine. Maybe it had an update and broke everything. Regardless, working now, thank you!
