### ISSUE TITLE
VSCode 1.71.0 broke buttons(close,minimize,maximize) Acrylic effect.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [illixion/vscode-vibrancy-continued#12]
![image](https://user-images.githubusercontent.com/75798544/188046401-dd844f85-8acd-4426-aeb9-d0bb4b4433c4.png)
![image](https://user-images.githubusercontent.com/75798544/188046518-d2c7691e-1b35-499f-a26f-05276a5bb9fb.png)

**Comment by PhoenixCODE2322** [comment]
the turned this feature off in 1.71.2 , maybe accidentally again , also this option is available in settings for toggling..

**Comment by h3ct0rjs** [comment]
Hi 👋 @illixion 
With version Version: 1.71.2 after you maximize the VSCode window this will disable the background transparency 
is this related or should I open a new issue?

Regards, 
H
