### ISSUE TITLE
[Bug]: I have some problem, transparency and Blur effect don't work anymore. 

### ISSUE THREAD

**Issue by ibandim123** [illixion/vscode-vibrancy-continued#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transparency effect and blur don't work anymore in my VS code workplace. Let's me show you whats happen : 
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/59544620/8482bcab-d99a-4023-8dd5-03238db3a089)
 
The letters are some delay 

### Environment

```markdown
- OS: Windows
- VSCode: yes
- Extension: ---
- Theme: Codex Effect
```

**Comment by illixion** [comment]
Duplicate of https://github.com/illixion/vscode-vibrancy-continued/issues/122

**Comment by ibandim123** [comment]
> Duplicate of #122

Oh, sorry.

**Comment by illixion** [comment]
No worries
