### ISSUE TITLE
[Bug]: Not working on mac os

### ISSUE THREAD

**Issue by SiddharthMathurDeveloper** [illixion/vscode-vibrancy-continued#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="511" alt="Screenshot 2024-02-06 at 10 52 59 PM" src="https://github.com/illixion/vscode-vibrancy-continued/assets/133037456/039b5c28-33e2-4b93-ae4c-e10de7b52685">

not working

### Environment

```markdown
- OS:Mac os latest one
- VSCode:
- Extension:
- Theme:
```

**Comment by illixion** [comment]
Please fill out the Environment field, especially the macOS and VSCode versions as well as the currently selected theme.

**Comment by SiddharthMathurDeveloper** [comment]
- OS: macOS Sonoma 14.2.1
- VSCode: latest
- Extension: latest
- Theme: Dark (subbar only)

extra info
 "vscode_vibrancy.theme": "Dark (Only Subbar)",
    "workbench.colorCustomizations": {
    },
    "workbench.colorTheme": "Ayu Dark"

**Comment by SiddharthMathurDeveloper** [comment]
OS: macOS Sonoma 14.2.1
VSCode: latest
Extension: latest
Theme: Dark (subbar only)
extra info
"vscode_vibrancy.theme": "Dark (Only Subbar)",
"workbench.colorCustomizations": {
},
"workbench.colorTheme": "Ayu Dark"

**Comment by illixion** [comment]
Looks like you’re using an unsupported VSCode theme (Ayu Dark), please check the list of supported themes in the description.

**Comment by TheFanatr** [comment]
Same issue here. Same environment as OP but on macOS Sonoma 14.3. This just happened with the latest update of Code; worked perfectly fine before.

```json
{
    "vscode_vibrancy.opacity": 0,
    "vscode_vibrancy.type": "ultra-dark"
    "workbench.colorTheme": "Monokai"
}```

**Comment by mklebrasseur** [comment]
> Same issue here. Same environment as OP but on macOS Sonoma 14.3. This just happened with the latest update of Code; worked perfectly fine before.
> 
> ```json
> {
>     "vscode_vibrancy.opacity": 0,
>     "vscode_vibrancy.type": "ultra-dark"
>     "workbench.colorTheme": "Monokai"
> }
> ```

Just when I was starting to enjoy VS Code 🤣, I also confirm that Vibrancy breaks with the latest update to vs code 1.86.1. 

Worked perfectly prior to updating.

**Comment by illixion** [comment]
@TheFanatr can you post your current Vibrancy Continued version? The issue is because you're using the `ultra-dark` vibrancy type, which was deprecated in VSCode 1.86, and Vibrancy is supposed to detect that and ask you to change it to `under-window`.

**Comment by mklebrasseur** [comment]
I've tried `under-window` and `auto`. I know this is directly for @TheFanatr but my version of Vibrancy is 1.1.27. If you prefer I open my own issue I am happy to do so!

```
{
  "vscode_vibrancy.opacity": 0,
  "vscode_vibrancy.theme": "GitHub Dark Default",
  "vscode_vibrancy.type": "under-window"
}
 ```

**Comment by illixion** [comment]
@mklebrasseur No worries, could you try reinstalling VSCode perhaps? Also, are you using any extensions that modify VSCode's files like APC or VSCode Animations?

**Comment by mklebrasseur** [comment]
> @mklebrasseur No worries, could you try reinstalling VSCode perhaps? Also, are you using any extensions that modify VSCode's files like APC or VSCode Animations?

I disabled all plugins, I do not have APC or VSCode Animations installed. While looking at the console logs I can Vibrancy is initialized and no other errors are observed. 

I did attempt a reinstall last evening but some files were still lingering. I will attempt it again and report back!

**Comment by mklebrasseur** [comment]
@illixion a full uninstall and clearing of some lingering cache folders / saved states seems to have restored the functionality!

Thanks!

**Comment by current** [comment]
> @illixion a full uninstall and clearing of some lingering cache folders / saved states seems to have restored the functionality!
> 
> Thanks!

what folders did you have to delete? im having troubles aswell, deleted the application support folder for Code and ~/.vscode

**Comment by mklebrasseur** [comment]
> > @illixion a full uninstall and clearing of some lingering cache folders / saved states seems to have restored the functionality!
> > Thanks!
> 
> what folders did you have to delete? im having troubles aswell, deleted the application support folder for Code and ~/.vscode

@current I ran through the following

1. Close and Quit VSCode
2. Remove VScode from Applications (just go to Finder -> Applications and move VSCode to Bin)

3. Execute these commands in any order. The paths might be slightly different for you. 
```
rm -fr ~/.vscode*
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist 
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
```

4. Reinstall VSCode

**Comment by mhjiang97** [comment]
> @illixion might related to this issue, on my mac, it looks like this ![image](https://private-user-images.githubusercontent.com/45580554/306542204-88d5d3f2-866a-4b11-a670-8b19ef11f9e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzQ1NTQsIm5iZiI6MTcwODY3NDI1NCwicGF0aCI6Ii80NTU4MDU1NC8zMDY1NDIyMDQtODhkNWQzZjItODY2YS00YjExLWE2NzAtOGIxOWVmMTFmOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNzE3MDdjOTExY2Q2OWU2NWNmMzU1NWM0Njc3Y2Y2YjI2MjdkNGNlNGM3YmY0ZDc2MmIzOWIyZjRhZDM3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qVHN9cHxyGC0-ZhDQRHzkmY6te80xgzKgVpB4xALzjc)
> 
> is it also caused by the cache?

The same for me. Have you found a way to fix this? Thanks.

**Comment by kamilali** [comment]
> > @illixion might related to this issue, on my mac, it looks like this ![image](https://private-user-images.githubusercontent.com/45580554/306542204-88d5d3f2-866a-4b11-a670-8b19ef11f9e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzQ1NTQsIm5iZiI6MTcwODY3NDI1NCwicGF0aCI6Ii80NTU4MDU1NC8zMDY1NDIyMDQtODhkNWQzZjItODY2YS00YjExLWE2NzAtOGIxOWVmMTFmOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNzE3MDdjOTExY2Q2OWU2NWNmMzU1NWM0Njc3Y2Y2YjI2MjdkNGNlNGM3YmY0ZDc2MmIzOWIyZjRhZDM3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qVHN9cHxyGC0-ZhDQRHzkmY6te80xgzKgVpB4xALzjc)
> > is it also caused by the cache?
> 
> The same for me. Have you found a way to fix this? Thanks.

@Rey-Wang and @mhjiang97 - I had this issue as well. The solution was to make sure that the theme you have for VSCode doesn't inherit from system theme (if you're on auto) or is set to light theme. It seems to work properly only with dark theme. Hope that works for yall!

**Comment by mhjiang97** [comment]
@kamilali THANK YOU~

**Comment by illixion** [comment]
Closing as stale.
