### ISSUE TITLE
[Bug]: Transparency effect not working

### ISSUE THREAD

**Issue by keplerHaloxx** [illixion/vscode-vibrancy-continued#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: Windows 11 22H2 22621
- VSCode: 1.86.1
- Extension: 1.1.27
- Theme: Dark+
```

### Anything else?

My VSCode editor looks like this and everything else is just the normal Dark+ theme with no transparency effect
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/80098945/55fd7185-fc65-4990-93e9-0402c84f3816)

**Comment by LuigiDaBro** [comment]
See [[Bug]: VSCode 1.86.0 on Windows is incompatible (blurry text when scrolling) #122](https://github.com/illixion/vscode-vibrancy-continued/issues/122).

**Comment by keplerHaloxx** [comment]
> See [[Bug]: VSCode 1.86.0 on Windows is incompatible (blurry text when scrolling) #122](https://github.com/illixion/vscode-vibrancy-continued/issues/122).

Sorry for the late reply but this worked!
