### ISSUE TITLE
[Bug]: 'Reload Vibrancy' Failing. Need 'administrator privileges'

### ISSUE THREAD

**Issue by sleipner01** [illixion/vscode-vibrancy-continued#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing the extension, clicking Cmd + Shifft + P, and executing 'Reload Vibrancy', I get an error.

![Screenshot 2024-02-22 at 08 36 33](https://github.com/illixion/vscode-vibrancy-continued/assets/92637738/d85beb73-7617-4245-a0ae-2cdd2e49de57)

The command 'Reload Vibrancy' is denied execution.
Looking at the details, I apparently need to run the command with 'administrator privileges'.

![Screenshot 2024-02-22 at 08 36 57](https://github.com/illixion/vscode-vibrancy-continued/assets/92637738/8bf7d245-35ae-4532-8eaa-6654933ea94a)

### Expected Behavior

VSCode to Reload with Vibrancy Continued config

### Steps To Reproduce

1. Follow installation procedure
2. Run 'Reload Vibrancy'

### Environment

```markdown
- OS: macOS Sonoma 14.2 (23C64)
- VSCode: 1.86.2 (Universal)
- Extension: 1.1.27
- Theme: Dark+
```

**Comment by illixion** [comment]
Seems like your installation of VSCode is owned by another user, run the following command in the Terminal app to take ownership of the files, and enter your password when asked: `sudo chown -R $(whoami):staff "/Applications/Visual Studio Code.app/"`

**Comment by sleipner01** [comment]
The command didn't work, but uninstalling VSCode, doing a restart and installing it again fixed the problem. Thanks!
