### ISSUE TITLE
[Bug]: "workbench.html file is different from what is expected" // Vibrancy Continued not working on MacOS

### ISSUE THREAD

**Issue by WeLeBro** [illixion/vscode-vibrancy-continued#135]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I have tried just about everything, and looked through every solution provided on this page but nothing seems to do the trick. Every time I try to get it to work I get the following message:

![error_vibrancy_continued](https://github.com/illixion/vscode-vibrancy-continued/assets/70779688/31d3265b-9134-4ef2-a0ea-53592689e1d5)

I have tried:
- Reinstalling VS Code
- Clearing VS Code's cache
- Disabling all other installed extensions and going through the entire installation process again
- Making sure that I have administrative rights to VS Code
- Watching multiple different tutorials online & reading forums

Nothing seems to be out of the ordinary in my Workbench settings. Yet I can't figure it out, so I'm here to see if you guys know any ways of resolving the issue and whether it is down to something on my system or a bug in Vibrancy Recontinued.

### Expected Behavior

I expected the background to change to a translucent state, instead, it stayed solid whatever parameters I tried to change and every time the error message showed up again.

### Steps To Reproduce

1. Select _Dark+_ as VS Code theme.
2. Install: _Vibrancy Continued_
3. Reload _Vibrancy Continued_
4. Restart VS Code
![error_vibrancy_continued](https://github.com/illixion/vscode-vibrancy-continued/assets/70779688/f6a59288-fb6d-4c4f-bba9-605633b75335)

### Environment

```markdown
- OS: MacOS Sonoma 14.3.1 (23D60)
- VSCode: 1.86.2
- Extension: 1.1.27
- Theme: Dark+
```

**Comment by illixion** [comment]
I'm unable to reproduce this issue, type this command into a Terminal and paste the output here, preferably as a code block:

```bash
cat "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html"
```

**Comment by WeLeBro** [comment]
Sorry for the late response, I had a busy week at school. Here is the output of your command;

`
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta
			http-equiv="Content-Security-Policy"
			content="
				default-src
					'none'
				;
				img-src
					'self'
					data:
					blob:
					vscode-remote-resource:
					vscode-managed-remote-resource:
					https:
				;
				media-src
					'self'
				;
				frame-src
					'self'
					vscode-webview:
				;
				script-src
					'self'
					'unsafe-eval'
					blob:
				;
				style-src
					'self'
					'unsafe-inline'
				;
				connect-src
					'self'
					https:
					ws:
				;
				font-src
					'self'
					vscode-remote-resource:
					vscode-managed-remote-resource:
					https://*.vscode-unpkg.net
				;
				require-trusted-types-for
					'script'
				;
				trusted-types
					amdLoader
					cellRendererEditorText
					defaultWorkerFactory
					diffEditorWidget
					diffReview
					domLineBreaksComputer
					dompurify
					editorGhostText
					editorViewLayer
					notebookRenderer
					stickyScrollViewLayer
					tokenizeToString
				;
		"/>
	</head>

	<body aria-label="">
	</body>

	
	<script src="workbench.js"></script>
</html>`

**Comment by illixion** [comment]
Your file appears to be correct, so you shouldn't be getting this message. This error is also triggered if the function that writes to the file fails, so it's possible that this file isn't writable by your user account for some reason. You can check by running this terminal command:

```
test -w "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html" && echo "Writable" || echo "Not Writable"
```

**Comment by WeLeBro** [comment]
It does say 'Writable' when I put in that command into the terminal. So do you know if anything else could be going wrong? A setting maybe?

**Comment by illixion** [comment]
I'm not sure what else might be going wrong. You could try running the extension locally using VSCode's debugging tools to check what the cause of the error is:

1. Clone this repository and open it in VSCode (`git clone https://github.com/illixion/vscode-vibrancy-continued.git && code vscode-vibrancy-continued`)
2. Open `extension/index.js` and select line 319 (`if (HTML !== newHTML) {`)
3. Press F9 to set a breakpoint and then press F5, when asked for a debugging option choose VS Code Extension Development
4. In a new VSCode window that pops up, bring up command palette and choose Reload Vibrancy
5. In the original window, step through the code by pressing F10 until you encounter an error
6. Check what the error is on the left panel that lists variables and post it here

**Comment by wanan-life** [comment]
@WeLeBro It seems that reinstalling vscode can solve this problem, and that's how I solved it.

**Comment by illixion** [comment]
Closing as stale, feel free to reopen if this is still an issue.

**Comment by mortum5** [comment]
I've also encounter the same problem. Dont know how to reproduce because ive mase a several chaotic step. Problem first apears when i try install Vibrancy also in my second profile. And after that it cant start, but i dont want to reinstall vs code also

**Comment by illixion** [comment]
@mortum5 please run these commands in a terminal and post the output here:

```shell
cat "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html"

test -w "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html" && echo "Writable" || echo "Not Writable"
```

Reinstalling VSCode is as simple as running the VSCode installer, and you won't lose any data, but it's up to you.

**Comment by mortum5** [comment]
Oh. Ive already replace vs code app. And now everything work in two profiles.

**Comment by mortum5** [comment]
@illixion Hello again. 

I think that problems arises in conjunction with the extension https://marketplace.visualstudio.com/items?itemName=BrandonKirbyson.vscode-animations.

When the first thing is the extension for animation, I understand it changes the workbench, and then this extension, it cusses that the file has been changed.

What do you think?

**Comment by BitCalSaul** [comment]
> Your file appears to be correct, so you shouldn't be getting this message. This error is also triggered if the function that writes to the file fails, so it's possible that this file isn't writable by your user account for some reason. You can check by running this terminal command:
> 
> ```
> test -w "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html" && echo "Writable" || echo "Not Writable"
> ```

can't we install other extensions that modify workbench.html?
