### ISSUE TITLE
[Bug]: Doesn't work on VSCode 1.87.0

### ISSUE THREAD

**Issue by seabo** [illixion/vscode-vibrancy-continued#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

VSCode updated to 1.87.0 and now Vibrancy doesn't seem to work.

### Environment

```markdown
- OS: MacOS (Ventura 13.0.1)
- VSCode: 1.87.0 (commit 019f4d1419fbc8219a181fab7892ebccf7ee29a2)
- Extension: 1.1.27
- Theme: Default Dark
```

**Comment by illixion** [comment]
I'm also on 1.87.0 and Vibrancy is working fine for me. Can you describe the issue in more detail, troubleshooting steps you've taken, etc? You can also try to reinstall VSCode as that seems to work for many people encountering issues after updates.

**Comment by seabo** [comment]
Thanks for the quick response. 

I did already try reinstalling VSCode and reinstalling the extension but neither fixed the issue. Following the update to 1.87.0 when I restarted VSCode this morning, the vibrancy effect no longer works - modifying the opacity setting has no effect (the window is fully opaque at all times).

**Comment by illixion** [comment]
Can you check the value for the setting "Vibrancy: Type" (`vscode_vibrancy.type`) and post it here? Also, make sure that you don't have transparency disabled globally through accessibility settings.

**Comment by sahinyakici** [comment]
Hey, i have to same problem. My env:

> Version: 1.87.1 (user setup)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:36.258Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

Also my screen get a little bit weird like this:
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/65544443/ced0d7ac-2619-420c-82cd-4292a3d33644)

There is constant forgy. Finally i can't find "vscode_vibrancy.type" in settings.json. Just added this : "vscode_vibrancy.imports": ["/path/to/file"]

**Comment by illixion** [comment]
@sahinyakici please check pinned issues: https://github.com/illixion/vscode-vibrancy-continued/issues/122

**Comment by sahinyakici** [comment]
@illixion Thank you. but I guess I'll wait for the extension to work on 1.87.1.

**Comment by Oolix** [comment]
Doesn't seem to be fixed in 1.87.1 or 1.87.2 😢

**Comment by illixion** [comment]
> Doesn't seem to be fixed in 1.87.1 or 1.87.2 😢

Are you referring to the macOS or Windows issue?

**Comment by Oolix** [comment]
> > Doesn't seem to be fixed in 1.87.1 or 1.87.2 😢
> 
> Are you referring to the macOS or Windows issue?

Windows. Wrong issue, whoops!

**Comment by seabo** [comment]
> Can you check the value for the setting "Vibrancy: Type" (vscode_vibrancy.type) and post it here? Also, make sure that you don't have transparency disabled globally through accessibility settings.

For me, the `vscode_vibrancy.type` setting is `auto`.

**Comment by illixion** [comment]
Closing as stale, if this is still an issue for you, please make sure that you don't have "Reduce transparency" enabled in macOS Accessibility settings and reopen.
