### ISSUE TITLE
[Bug]: Even after uninstalling the plugin, it cannot be maximized

### ISSUE THREAD

**Issue by shaobeichen** [illixion/vscode-vibrancy-continued#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even after uninstalling the plugin, it cannot be maximized

Originally, it could have been maximized, but now it's not possible to uninstall it after installation

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

```markdown
- OS: windows10
- VSCode: 1.86
- Extension:
- Theme:
```

### Anything else?

-

**Comment by illixion** [comment]
Please check the description: https://github.com/illixion/vscode-vibrancy-continued#how-to-uninstall-vibrancy

> **How to uninstall Vibrancy?**
> Press F1 or ⌘+Shift+P and activate command "Disable Vibrancy", then restart Visual Studio Code.
