### ISSUE TITLE
[Bug]: Terminal is not blur / transparent

### ISSUE THREAD

**Issue by liloche** [illixion/vscode-vibrancy-continued#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The terminal of VSCode is always of the color of the Theme. I tested with many Themes you suggested and there is the same issue with all.
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/67659818/e21e278f-372b-456d-b571-6dca8064ada9)

### Expected Behavior

I expect to have the terminal in blur / transparent effect.

### Environment

```markdown
- OS: Windows 11 23H2
- VSCode: 1.85.2
- Extension: 1.1.29
- Theme: Tokyo Night Storm
```

**Comment by illixion** [comment]
Please check FAQ: https://github.com/illixion/vscode-vibrancy-continued#effect-doesnt-work-for-terminal
