### ISSUE TITLE
[Bug]: auto dark mode wrong behavior

### ISSUE THREAD

**Issue by rainbowflesh** [illixion/vscode-vibrancy-continued#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![QQ截图20240505182958](https://github.com/illixion/vscode-vibrancy-continued/assets/20819692/0995a9eb-a1c3-4d39-9f81-f4b9b5b31da1)

1. When system change to light/dark mode with VS Code running, extension will notify theme changed and pop up reload dialog; but after restart, the "config is changed" dialog will pop up again with change back to opposite theme.
2. When system change to light/dark mode without VS Code running, extension won't prompt change to light/dark mode.

### Expected Behavior

A light/dark mode check after VS Code start up will help?

### Steps To Reproduce

1. close vscode.
2. change system theme.
3. run vscode.

### Environment

```markdown
- OS: win11
- VSCode: newest release
- Extension: alot
- Theme: rosepine
```

### Anything else?

```json
{
"vscode_vibrancy.theme":"light",
"vscode_vibrancy.preferedLightTheme":"light",
"vscode_vibrancy.preferedDarkTheme":"dark",
"window.autoDetectColorScheme":true
}
```

**Comment by MrOxMasTer** [comment]
The github theme is breaking too

![image](https://github.com/illixion/vscode-vibrancy-continued/assets/59291123/db58c0b4-7ea5-4c8f-be21-f71f02779407)

**Comment by LiPingYen** [comment]
The solarized dark + is broken.

![CleanShot 2024-05-05 at 20 58 49@2x](https://github.com/illixion/vscode-vibrancy-continued/assets/47491041/f1bdd128-957d-45ff-a025-e5b0b94848a6)

**Comment by zedle** [comment]
Same here with Catppuccin Mocha. If I set the theme again it will work until I load a new folder, reload the workspace, or restart vscode, then it breaks again.

**Comment by Fefedu973** [comment]
Same

**Comment by LouisRaverdy** [comment]
Same issue here, the only workaround is downgrading the version on install.
Waiting for a fix

**Comment by illixion** [comment]
Apologies all, pushed some bad code, version .31 has the fix

**Comment by LouisRaverdy** [comment]
Nice ! Thank you for your great extension !

**Comment by illixion** [comment]
The Vibrancy theme setting needs to be restored to what it was before as the previous value would've been lost, unfortunately

**Comment by Fefedu973** [comment]
> The Vibrancy theme setting needs to be restored to what it was before as the previous value would've been lost, unfortunately

Yup. Only issue. It seems that now the window control isn't working (cannot click on the maximize button and cannot snap the window on the sides)

**Comment by illixion** [comment]
> Yup. Only issue. It seems that now the window control isn't working (cannot click on the maximize button and cannot snap the window on the sides)

If you’re on Windows, you may be encountering this bug: https://github.com/illixion/vscode-vibrancy-continued/issues/140
