### ISSUE TITLE
[Bug]: VS Code is corrupted, try reinstalling

### ISSUE THREAD

**Issue by Dtar380** [illixion/vscode-vibrancy-continued#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I install and select Vibrancy as the theme and reload, a toast appears saying that the installation is corrupted, that I should reinstall VS Code, and the problem it comes with is that it doesnt let me manage the window of VS Code, it stops being resizable.

### Steps To Reproduce

1. Fresh install VsCode
2. Install Virancy
3. Turn it on
4. Reload VsCode
5. Read toast

### Environment

```markdown
- OS: Windows 11 23H2
- VSCode: VS Code 1.90.1
- Extension:
 - Vibrancy
 - Material Icon Theme
 - Better Comments
 - Code Snap
 - Error Lens
 - Intelli Code
 - IntelliCode API
 - Prettier
 - Spanish Language Pack
 - Code Spell Checker
 - Spanish Code Spell Checker
- Theme: Vibrancy on fresh install
```

**Comment by illixion** [comment]
Please read the top of the description:

> # Important notice for Windows users
> VSCode 1.86 and newer has known issues on Windows 10/11 due to Electron 27 introducing breaking changes to how transparent windows are handled. Your VSCode windows will **not be snappable or maximizable** if Vibrancy is applied on Windows, and you must also use "custom" for `window.titleBarStyle` setting. Some users have reported that [AltSnap](https://github.com/RamonUnch/AltSnap) may be able to solve this issue.
> If this is undesired, please downgrade to VSCode 1.85.2, which can be downloaded using this URL: https://update.code.visualstudio.com/1.85.2/win32-x64-user/stable

---

> # "Your VSCode installation appears to be corrupt"
> This extension works by editing VS Code's checksum-verified HTML files, which means that a warning prompt will appear after installing and enabling Vibrancy Continued. This warning is safe to disregard, and all changes can be reverted. Click on the cogwheel and select **Don't Show Again** to hide it.

I will amend the Windows notice with a warning that resizing might also stop working though, since this has been reported multiple times. You can either downgrade your VSCode version, or use the F1 menu action "Disable Vibrancy" to fully revert all changes.
