### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by marwan-sam** [illixion/vscode-vibrancy-continued#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i can't get full view for vs-code, it's smooth for moving vs-code window for windows 10 OS, when i click on maximize button on window it doesn't work

### Environment

```markdown
- OS: windows 10 
- VSCode: Setup-x64-1.92.2
- Extension: Vibrancy Continued
- Theme: Dark+ def.
```

### Anything else?

You can try it, I can't recommend it, it won't show up in the video for you.

**Comment by illixion** [comment]
Please check top of the extension's description for an explanation: https://github.com/illixion/vscode-vibrancy-continued#%EF%B8%8F-important-notice-for-windows-1011-users

Duplicate #140
