### ISSUE TITLE
[Bug]: Command 'Reload Vibrancy' resulted in an error

### ISSUE THREAD

**Issue by michaelberge8** [illixion/vscode-vibrancy-continued#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Restarted VS Code, then went to run the 'Reload Vibrancy' command and it resulted in a popup:
```
Command 'Reload Vibrancy' resulted in an error
A system error occurred (EACCES: permission denied, open '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js')
```

### Expected Behavior

It should reload VS Code and it should work

### Environment

```markdown
- OS:
Mac Sonoma 14.6.1

- VSCode:
Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

- Extension:
Vibrancy Continued

- Theme: N/A
```

**Comment by illixion** [comment]
Your installation of VSCode is likely owned by another user, run the following command in the Terminal app to take ownership of the files, and enter your password when prompted: `sudo chown -R $(whoami):staff "/Applications/Visual Studio Code.app/"`
