### ISSUE TITLE
[Bug]: MacOS (14.7) works 20% of the times I open it. VSCode 1.93.1

### ISSUE THREAD

**Issue by panoslymperopoulos** [illixion/vscode-vibrancy-continued#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So i try to use this extension, (that I really really love) for a year now, and I revisited to try again.

the only way to make it work somehow, is to restart my Mac, and instantly open VSCode. if i close and re-open the VSCode then poof...won't work anymore. I even tried to download and debug it a bit, or use the CSS code of the theme directly injected into the CSS of the VSCode.

and i tried everything in the documentation. and I also searched in the issues and did not find anything related. seriously i can't be the only one. more people on google have it

i provide the video below:

https://github.com/user-attachments/assets/f83e1ea2-68f0-4511-b35f-a2249119c4c8

are there any logs that i can provide? and where to find them? 
also, if i want to experiment myself, how to compile it and use it in vscode? thank you in advance you guys!

edit: these are the log of extensions as I load vscode. maybe on of them come in conflict?

<img width="1437" alt="SCR-20241003-udsd" src="https://github.com/user-attachments/assets/ed3ee156-c267-48c9-a07d-cc5d99ce4445">

and this is my settings.json

[settings.json](https://github.com/user-attachments/files/17249734/settings.json)

### Expected Behavior

it should work everytime without OS restart

### Environment

```markdown
- OS: MacOS 14.7
- VSCode: 1.93.1 (latest)
- Extension: 1.1.37
- Theme: Dark+
```

### Anything else?

thank you so much for your effort guys, this extension is a must have for me, and my colleagues!

**Comment by illixion** [comment]
Just to make sure, does this occur if you quit out of VSCode and re-launch? Also, VSCode v1.94 was recently released, so I'd advise updating to make sure this issue wasn't fixed in a newer version.

> are there any logs that i can provide? and where to find them?

You can invoke the Developer Tools via the command palette (Cmd+Shift+P) and check the Console tab for any VSCode logs, or use [Debugtron](https://github.com/pd4d10/debugtron) to get Electron logs.

> how to compile it and use it in vscode?

You can clone this repo, open it in VSCode and press F5 while editing `extension/index.js` to start a VSCode instance with a development version of the code. To compile it into a VSIX, you can use the `vsce package` command.

**Comment by panoslymperopoulos** [comment]
@illixion  this is indeed happening from quit and relaunching. i updated to VSCode 1.94 now is working 0%.

in the last case though, even though i managed to get it run by accident, when i opened a new window (cmd+shift+N), extension wasn't applied either.

Developer tools showed nothing, only the "Buffer()" is deprecated warning. (this was in console either when it worked or not).

this is really sad for me, because this extension really helps my productivity. no joke :D

**Comment by panoslymperopoulos** [comment]
Hallelujah !!!!!! it seems that after updating, i forgot to "reload vibrancy" now it is 100% consinstent!!!!! oh boy oh boy!!!

thank you for your answer @illixion , and let's hope this holds on through time!

**Comment by illixion** [comment]
Glad to hear! Hope it continues to work well for you in the future
