### ISSUE TITLE
[Bug]: Not working on Windows VSCode 1.94

### ISSUE THREAD

**Issue by BlackC-Y** [illixion/vscode-vibrancy-continued#166]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After updating vscode, the extension installs fine with no errors, but no effect

Have tried reinstalling vscode and extensions, restoring vscode to default environment.
Transparency effect in system settings is turned on.

### Environment

```markdown
- OS: Win11 23H2
- VSCode: 1.94
- Extension: 1.139
- Theme: Default Dark+
```

**Comment by illixion** [comment]
Issue is related to VSCode switching to ESM for workbench html, will look into fixing this. I found this error by launching VSCode via the terminal so it prints the Electron log:

`(node:14176) UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, node, and electron are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`
