### ISSUE TITLE
[Bug]:Helppppppppppppppppppp

### ISSUE THREAD

**Issue by Zong0619** [illixion/vscode-vibrancy-continued#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: macos 15.0.1
- VSCode: 1.94.2
- Extension: v1.1.41
- Theme: Dracula Theme Official
```

### Anything else?

![Pasted Graphic](https://github.com/user-attachments/assets/59f54b8a-f01a-47e3-9868-83065dfff0d2)

**Comment by illixion** [comment]
Please ensure you're using the same theme in Vibrancy as in VSCode, in your case you're using a Light VSCode theme with a Dark Vibrancy theme, and you should change the Vibrancy theme to Default Light. You can also use the auto switch feature if you have auto detection of color scheme enabled.

**Comment by Zong0619** [comment]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/e0a73f4f-7120-45c9-a22c-7d440d6a186b">
After I switched the VScode theme to the same as the Vibrancy theme, my VScode still had a white fog.

**Comment by illixion** [comment]
Seems like the VSCode theme you're using is too different and is thus incompatible, here's the list of supported VSCode themes: https://github.com/illixion/vscode-vibrancy-continued?tab=readme-ov-file#vscode_vibrancytheme

**Comment by Zong0619** [comment]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/57e0fb05-7bc5-41d1-8d53-34d43edafc99">
I still have the same problem with Default Dark ; _ ;

**Comment by Zong0619** [comment]
I ran it successfully one year ago, but suddenly one day it became like this. I was not sure whether it was caused by a plug-in conflict or a certain update until I wanted to use Vibrancy again today...

**Comment by illixion** [comment]
Could you post your full Vibrancy configuration? I think your Vibrancy type might be incorrect, as some of them replicate a light mode

**Comment by Zong0619** [comment]
<img width="925" alt="image" src="https://github.com/user-attachments/assets/5c0b3607-a9e9-4b59-830a-5bc0323deffc">
<img width="304" alt="image" src="https://github.com/user-attachments/assets/1b0a74d7-b9a3-4112-937c-fe0cc3246f14">
this one?

**Comment by Zong0619** [comment]
<img width="139" alt="image" src="https://github.com/user-attachments/assets/09e44950-7e44-44e1-8e26-4c2f13131743">
<img width="134" alt="image" src="https://github.com/user-attachments/assets/29850ea7-fcb1-4d5a-9562-6817f005e508">
<img width="134" alt="image" src="https://github.com/user-attachments/assets/2eb8b1a9-6ac8-4a4a-ae42-f0324e944b16">
<img width="139" alt="image" src="https://github.com/user-attachments/assets/3c19ca76-e459-4891-9950-d199e691cf87">
and there are all my plugins, if there are plugins that may cause conflicts

**Comment by illixion** [comment]
Try disabling `vscode_vibrancy.enableAutoTheme`, this bug can occur when you're using a light Vibrancy theme with a dark VSCode theme, which is likely what's happening here. If you didn't enable `window.autoDetectColorScheme`, VSCode might be reporting that you're always in light mode.

**Comment by Zong0619** [comment]
I fixed it!!!!!
Thank you very much, 
<img width="371" alt="image" src="https://github.com/user-attachments/assets/70723ddc-8a2f-41dc-a840-356ec1d86ae5">
The problem is this

**Comment by Zong0619** [comment]
<img width="572" alt="image" src="https://github.com/user-attachments/assets/6b86d96b-d3f8-4108-99d3-a1f3939a7319">
I would like to know what is the best setting for macos

**Comment by Zong0619** [comment]
Thank you very much
