### ISSUE TITLE
[Bug]: The black edge of the terminal font when the theme is "Default Light+"

### ISSUE THREAD

**Issue by hqc8848** [illixion/vscode-vibrancy-continued#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just as the title, there's black edge of the terminal font when the theme is "Default Light+".

### Expected Behavior

I don't want to see the black edge any more, that's it.

### Steps To Reproduce

1. Set your theme to "Default Light+"
2. Open your terminal in VS Code
3. See error

### Environment

```markdown
- OS: macOS 14.4.1
- VSCode: 1.94.2
- Extension: 1.1.41
- Theme: Default Light+
```

### Anything else?

Font: Maple Mono NF CN v7.0-beta28 (see [subframe7536/maple-font](https://github.com/subframe7536/maple-font "Click to view"))

Setting:
```json
{
    "vscode_vibrancy.enableAutoTheme": true,
    "vscode_vibrancy.opacity": 0,
    "window.autoDetectColorScheme": true
}
```

**Comment by hqc8848** [comment]
Here's what happened:
<img width="387" alt="Screenshot" src="https://github.com/user-attachments/assets/e3561df6-9163-4db2-be02-08f4d8734232">

**Comment by illixion** [comment]
I'm unable to reproduce this on my macOS 15.0.1 machine. Could you confirm whether this is happening when Vibrancy isn't enabled? Also, please share your entire VSCode config (you can use https://gist.github.com), it's possible that you have some font-related setting like the font weight or font family set incorrectly.

<img width="805" alt="Screenshot 2024-10-27 at 10 32 34" src="https://github.com/user-attachments/assets/e1d79073-413c-4149-9736-b4676d56745c">

**Comment by hqc8848** [comment]
I can't figure how to disable the Vibrancy, but I can show you my setting:
[settings.json](https://github.com/user-attachments/files/17533314/settings.json)

**Comment by illixion** [comment]
To disable Vibrancy, press F1 or ⌘+Shift+P and activate command "Disable Vibrancy", then restart Visual Studio Code.

The issue on your side is actually caused due to missing `"terminal.integrated.gpuAcceleration": "off"` in settings.json, Vibrancy is supposed to automatically set this value, but for some reason this didn't occur in your case. Try adding it to your settings and let me know if it works.

**Comment by hqc8848** [comment]
Thanks, it works ;)
