### ISSUE TITLE
[Bug]: Exception display

### ISSUE THREAD

**Issue by Web-Coke** [illixion/vscode-vibrancy-continued#172]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

After I updated the latest Vscode, the effect could not be applied normally, please see the screenshot for details

### Steps To Reproduce

1.Install the latest vscode on Win10
2.Reload Vibrancy

### Environment

```markdown
- OS:Win10 22H2
- VSCode:1.95.1
- Extension:v1.1.41
- Theme:All Theme
```

### Anything else?

![image](https://github.com/user-attachments/assets/81107929-e738-4f6c-8987-7c5c89fc5571)

**Comment by illixion** [comment]
I'm unable to reproduce this on my end, could you share your VSCode config?

**Comment by Web-Coke** [comment]
> I'm unable to reproduce this on my end, could you share your VSCode config?

Sorry to bother you, now the issue has been resolved. This problem occurred when I updated from 1.95.0 to 1.95.1 in vsocde, I tried `Reload Vibrancy` and `Disable Vibrancy` and then `Enable Vibrancy` but it didn't work, until I re-downloaded and installed vsocde on the official website. This problem was caused by updating in vsocde, this is a very strange bug.

Finally, thank you very much for your answer, and I wish you a happy life.

My English is not very good, if there is anything inappropriate, please bear with me, and thank you again.

**Comment by Web-Coke** [comment]
Thank you maintainers for your hard work, thank you!

**Comment by illixion** [comment]
No problem, glad to hear that it works now!
