### ISSUE TITLE
Unsupported operating system, Microsoft remote server support.

### ISSUE THREAD

**Issue by ShayBox** [illixion/vscode-vibrancy-continued#22]
When using any of Microsoft's remote server extensions (SSH/Container/WSL) this extension only reports as install-able to remote servers extensions list, there's some way to mark your extension as local only so it installs to the local vscode client but I don't know exactly how, other extensions do this.

**Comment by illixion** [comment]
Thanks for letting me know about this, I've found the relevant parameter to force the extension to run only on the local machine, will release an update that includes it.
