### ISSUE TITLE
How to enable acrylic?

### ISSUE THREAD

**Issue by SinanAkkoyun** [illixion/vscode-vibrancy-continued#23]
Hi, I'm on windows 11 and for me it's only using the Mica effect.
How can I change that to acrylic?

Thanks

**Comment by PhoenixCODE2322** [comment]
> 

can you post screenshot of whole desktop with VSCode ..

**Comment by PhoenixCODE2322** [comment]
> Hi, I was fooled, it is acrylic effect and not mica. However, can I somehow change the opacity and blurryness?

go into extension find the vscode vibrancy extension, click on the gear icon near it and select extension settings and you can change the things there.

**Comment by illixion** [comment]
Sounds like this question has been answered, thanks @PhoenixCODE2322!
