### ISSUE TITLE
Can't reload Vibrancy on Macbook M1

### ISSUE THREAD

**Issue by t-h-phuc96-work** [illixion/vscode-vibrancy-continued#30]
![image](https://user-images.githubusercontent.com/113356988/195242872-571cb967-71b9-49ef-9526-d7d81a2c52ad.png)

Error message: `Command 'Reload Vibrancy' resulted in an error (A system error occurred (EROFS: read-only file system, mkdir '/private/var/folders/qp/t8ngnpw938b098h1m78nvb9w0000gn/T/AppTranslocation/5A94F146-3BD2-414B-8133-FD6AOFFF5A59/d/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6'))`

Hi Team, this is what happened when I click reload Vibrancy, even though I followed the steps mentioned in the extension.
Thanks.

**Comment by illixion** [comment]
Hi,

Seems like your installation of VSCode is affected by App Translocation. To fix this, either use the Finder and move the VSCode to `/Applications` (or move it our of `/Applications` and then back in), or run the following command:

```shell
xattr -dr com.apple.quarantine "/Applications/Visual Studio Code.app"
```

**Comment by illixion** [comment]
Closing as stale, feel free to comment if this is still an issue.

**Comment by SergioEnrique** [comment]
This is happening to me with visual studio code insiders

**Comment by illixion** [comment]
> This is happening to me with visual studio code insiders

Did you try the troubleshooting steps mentioned in my earlier comments? This is a macOS issue and is unrelated to which version of VSCode you're currently using.

**Comment by t-h-phuc96-work** [comment]
thank you for supporting, but I don’t know if the issue is still there or
not, so I’ll get back to you if the issue happens again
