### ISSUE TITLE
Issue Template is missing

### ISSUE THREAD

**Issue by FahimFBA** [illixion/vscode-vibrancy-continued#31]
Hello,
The repository is currently missing the issue templates that might help others submit their issue in an organized way. If you would like to have them in your repository, then I would like to submit a pull request with some relevant issue templates. 

Let me know what you think about that.

**Comment by illixion** [comment]
Hi,

Thanks for letting me know about this, having an issue template would definitely be a good idea, I just haven't had the time to get around setting it up. I can write it myself, but I'd appreciate the help if you'd like to submit some as well, so feel free to go ahead with creating a PR.
