### ISSUE TITLE
[Bug]: vscode_vibrancy.imports not works

### ISSUE THREAD

**Issue by Rey-Wang** [illixion/vscode-vibrancy-continued#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I override some style in a custom css file, but not works
```
.monaco-list.settings-toc-tree .monaco-list-row.selected,
.monaco-list.settings-toc-tree .monaco-list-row.focused,
.monaco-list .monaco-list-row.selected,
.monaco-list.settings-toc-tree:not(.drop-target) .monaco-list-row:hover:not(.selected):not(.focused) {
  background: #528bff69 !important;
}
```
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/45580554/195800165-baaa2607-eb89-4edc-bf01-8a55e4ede842.png">

configuration:
```
  "vscode_vibrancy.imports": [
    "/Users/reywang/Documents/workHelpers/plugin-config/vscode_vibrancy_custom.css"
  ]
```

### Expected Behavior

<img width="433" alt="image" src="https://user-images.githubusercontent.com/45580554/195800734-d80312fb-315d-4070-85cb-5beff63fd3c2.png">

background color should be red

### Environment

```markdown
- OS: MacOS Monterey 12.4
- VSCode: Version: 1.72.2 (Universal)
- Extension:Vibrancy Continued v1.1.7
```

**Comment by illixion** [comment]
Thanks for the report, found the issue to have been caused by CSP, just pushed an update that should fix it. Feel free to reopen if you still encounter this issue.

**Comment by Rey-Wang** [comment]
@illixion which version would contain this fix?

**Comment by Rey-Wang** [comment]
@illixion for v1.1.8, still not works for me, should I reopen this issue?

**Comment by illixion** [comment]
Yes, v1.1.8 is the updated version. This error means that the extension couldn't read the file contents of your CSS file, make sure that the path is correct and is accessible. Also, make sure that VSCode is allowed to access the Documents folder through macOS privacy settings.
