### ISSUE TITLE
[Bug]: EACCES: permission denied

### ISSUE THREAD

**Issue by usamasaleem1** [illixion/vscode-vibrancy-continued#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Command 'Reload Vibrancy' resulted in an error (A system error occurred (EACCES: permission denied, mkdir '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6'))

### Environment

```markdown
- OS:
- VSCode:
- Extension:
```

### Anything else?

I have VSCode in my applications folder.

**Comment by illixion** [comment]
Seems like your VSCode was installed by another user, so your user account doesn't have permissions to modify it. To solve this, go to /Applications, find Visual Studio Code.app, right click → Get Info, and make sure that your account has Read & write permissions in the Sharing & Permissions section.

**Comment by alessandro-newzoo** [comment]
I'm having the same issue actually, and giving my user read/write permissions didn't help :(

**Comment by illixion** [comment]
Thanks for updating your comment, was about to ask if you're running Ventura as I haven't had the time to test it yet. Please try running these commands in the VSCode integrated terminal and post the output here:

```shell
stat "/Applications/Visual Studio Code.app/Contents/Resources/app/out/"
mkdir "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6"
touch "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6/index.js"
```

**Comment by alessandro-newzoo** [comment]
thanks for your prompt reply!

Here's the output:

```shell
❯ stat "/Applications/Visual Studio Code.app/Contents/Resources/app/out/"
16777234 3450645 drwxr-xr-x 12 root wheel 0 384 "Nov  4 11:30:12 2022" "Nov  4 11:30:12 2022" "Nov  4 11:30:12 2022" "Nov  1 23:51:22 2022" 4096 0 0 /Applications/Visual Studio Code.app/Contents/Resources/app/out/

❯ mkdir "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6"
mkdir: /Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6: Permission denied

❯ touch "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6/index.js"
touch: /Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6/index.js: No such file or directory
```

**Comment by illixion** [comment]
Interesting, your installation of VSCode seems to have been done by the root user. Did you use homebrew to install VSCode by any chance?

I've also just realized that my solution doesn't apply permissions to enclosed items, so to fix this run `sudo chown -R $(whoami):staff "/Applications/Visual Studio Code.app/"`.

There's currently a PR open that adds `sudo` support to this extension, I'll try to review it and merge as soon as I have time, as it should fix this issue properly.

**Comment by alessandro-newzoo** [comment]
> I've also just realized that my solution doesn't apply permissions to enclosed items, so to fix this run sudo chown -R $(whoami):staff "/Applications/Visual Studio Code.app/".

Yay this did the trick, thank you so much!

> Interesting, your installation of VSCode seems to have been done by the root user. Did you use homebrew to install VSCode by any chance?

I should have mentioned it's a company-managed laptop (even though I have root access myself), and VS Code has been installed through a portal-like app my company provides where you can choose what to install from a set of predefined apps. So yeah, it probably runs brew in the backend!

**Comment by illixion** [comment]
No problem, glad to hear that this is resolved!

**Comment by LamineGitHub** [comment]
@illixion 
Please, I have the same problem but on a windows

**Comment by illixion** [comment]
> @illixion
> Please, I have the same problem but on a windows

You probably have a system-wide installation of VSCode, run it as administrator before enabling Vibrancy.

**Comment by illixion** [comment]
> @illixion <img alt="image" width="575" src="https://user-images.githubusercontent.com/50121574/200329076-b38a4537-b51f-4a2b-b499-c817bc1690b5.png">
> 
> Unfortunately, the command you gave does not run on my M1 machine. What am I doing wrong?
> 
> In addition, all the other steps you asked for did not work either.

The command in your screenshot is different from the one I’ve provided, you need to copy and paste it exactly as it appears in my comment. Also, make sure that you’re not using smart quotes in your commands. As long as you copy directly from your web browser into the Terminal, you should be fine.

**Comment by Mr-Righteousdev** [comment]
I have the same issue of permission denied when i try reload vibrancy command but i am using kali linux some help please ...

**Comment by illixion** [comment]
> I have the same issue of permission denied when i try reload vibrancy command but i am using kali linux some help please ...

It's likely that VSCode files are owned by the root user on Kali Linux, you can run VSCode as root using `sudo`, or you can run `chown -R $(whoami) /path/to/vscode` on the directory where VSCode is installed to take ownership, it should also be in the error message.
