### ISSUE TITLE
[Bug]: 'editor.stickyScroll.enabled' No effect

### ISSUE THREAD

**Issue by SuperManito** [illixion/vscode-vibrancy-continued#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: Windows11
- VSCode: 1.73.1
- Extension:
```

**Comment by SuperManito** [comment]
Another problem

I using theme [One Dark Pro Italic Vivid](https://marketplace.visualstudio.com/items?itemName=jsjlewis96.one-dark-pro-italic-vivid)

Active line no effect

**Comment by illixion** [comment]
This theme is not supported, please check the list of supported themes here: https://github.com/illixion/vscode-vibrancy-continued#vscode_vibrancytheme

Also, just checked if sticky scroll works on my end, and I didn't encounter any issues.

**Comment by SuperManito** [comment]
> sticky scroll

`sticky scroll` also no effect in the default theme

**Comment by SuperManito** [comment]
> This theme is not supported, please check the list of supported themes here: https://github.com/illixion/vscode-vibrancy-continued#vscode_vibrancytheme
> 
> Also, just checked if sticky scroll works on my end, and I didn't encounter any issues.

`sticky scroll` also no effect in the default theme
