### ISSUE TITLE
[Bug]: Extension fails to launch 

### ISSUE THREAD

**Issue by MartinRybergLaude** [illixion/vscode-vibrancy-continued#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The extension fails to launch. The reason is likely found in commit 2857f2720efd6f2a38754ce070c534cff3e160a0 where a package called rifraf seems to have been installed instead of rimraf. Should be an easy fix!

### Expected Behavior

Extension should launch.

### Steps To Reproduce

Try to launch the extension.

### Environment

```markdown
- OS: MacOS
- VSCode: 1.73.1
- Extension: Vibrancy Continued
```

**Comment by nnamdiogbu** [comment]
Bummed, wanted to use this extension now. Easy fix, but probably won't be fixed anytime soon

**Comment by thisbejann** [comment]
Is this related to the error "Command 'Reload Vibrancy' resulted in an error (command 'extension.updateVibrancy' not found)?

**Comment by illixion** [comment]
Not sure how I managed to miss that, my bad, just pushed an update that fixes this.
