### ISSUE TITLE
Caption buttons not transparent

### ISSUE THREAD

**Issue by EmrecanKaracayir** [illixion/vscode-vibrancy-continued#48]
![image](https://user-images.githubusercontent.com/84916904/206644339-a5d27330-497c-47df-8717-af8159d42a20.jpeg)

Fresh Windows 11 install, fresh vs code install.

**Comment by EmrecanKaracayir** [comment]
Solved the problem myself. Go to your settings and in the window tab, untick the experimental window controls overlay.

![image](https://user-images.githubusercontent.com/84916904/206657954-c99f6400-fa4d-41dc-b88d-dea444841e82.jpeg)

**Comment by mvahaste** [comment]
If it's solved then close the issue, should be able to if you opened it.

**Comment by illixion** [comment]
Thanks for the info! Didn't realize that this was added as a user configurable setting, would be a good idea to add a check to make sure that it's disabled. I've created #49 to track this.

**Comment by bigplayer-ai** [comment]
Ok I found it:
window.experimental.windowControlsOverlay.enabled
"window.experimental.windowControlsOverlay.enabled": false
![image](https://user-images.githubusercontent.com/119108387/212871555-92ac81c4-9fe4-4a18-99a7-56057221ea98.png)
