### ISSUE TITLE
[Bug]: No longer works in macOs 13.1

### ISSUE THREAD

**Issue by morphisjustfun** [illixion/vscode-vibrancy-continued#50]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

It doesn't work even after enabling, reloading the theme.

### Steps To Reproduce

1. Enable extension
2. Reload
3. Nothing happens

### Environment

```markdown
- OS: macOs 13.1
- VSCode: 1.74.1
- Extension: 1.1.12
```

**Comment by morphisjustfun** [comment]
Somehow the update has messed up my viscose installation. I reinstalled everything and now it works properly. Thanks!!

**Comment by illixion** [comment]
No problem, glad to hear!
