### ISSUE TITLE
[Feature]: Automatic Theme based on light/dark mode in OS

### ISSUE THREAD

**Issue by arimal199** [illixion/vscode-vibrancy-continued#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by bigplayer-ai** [comment]
This is a must feature. 
switch vibrancy to light mode+
or dark mode+
based on VScode theme.

**Comment by bigplayer-ai** [comment]
Hey,
Can you implement this?

**Comment by illixion** [comment]
This isn’t something that I’m personally interested in implementing as I use VSCode exclusively in dark mode, so don’t expect it to be implemented any time soon, but pull requests are always welcome. Perhaps this can be done using a CSS media query and the VSCode setting you’ve mentioned.

**Comment by rainbowflesh** [comment]
There was an example https://github.com/danielgjackson/vscode-auto-dark-mode-windows/blob/master/extension.js

I would give a try later.

**Comment by illixion** [comment]
Implemented in PR #146 and available in version 1.1.30
