### ISSUE TITLE
[Bug]: VSCode Window Buttons are not affected by Vibrancy

### ISSUE THREAD

**Issue by bigplayer-ai** [illixion/vscode-vibrancy-continued#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After running/reloading Vibrancy extension
The buttons of VSCODE window does not change colors.
![image](https://user-images.githubusercontent.com/119108387/212772905-aa7b174b-44bc-44d8-9e9a-7cb1e9971dbd.png)

### Expected Behavior

After running/reloading Vibrancy extension
The buttons of VSCODE window does change colors.

### Steps To Reproduce

1) Reload vibrancy
2) The buttons of VSCODE window does change colors.

### Environment

```markdown
- OS: Windows 11 22H2 Build 22621.1105
- VSCode: 1.7.4.3
- Extension:v1.1.12
```

**Comment by illixion** [comment]
Please ensure that “experimental window controls” VSCode setting is disabled, as shown here: #49

**Comment by bigplayer-ai** [comment]
I don't have this option/setting in my VSCode!

**Comment by bigplayer-ai** [comment]
Ok I found it:
window.experimental.windowControlsOverlay.enabled
"window.experimental.windowControlsOverlay.enabled": false
![image](https://user-images.githubusercontent.com/119108387/212871555-92ac81c4-9fe4-4a18-99a7-56057221ea98.png)
