### ISSUE TITLE
[Bug]:  Fix WIki vscode_vibrancy.opacity Opacity of Vibrancy Effect.  value must be: -1 ~ 0 and not 0 ~ 1

### ISSUE THREAD

**Issue by bigplayer-ai** [illixion/vscode-vibrancy-continued#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Bug]:  Fix WIki vscode_vibrancy.opacity Opacity of Vibrancy Effect.  value must be: -1 ~ 0 and not 0 ~ 1

### Expected Behavior

[Bug]:  Fix WIki vscode_vibrancy.opacity Opacity of Vibrancy Effect.  value must be: -1 ~ 0 and not 0 ~ 1

### Steps To Reproduce

[Bug]:  Fix WIki vscode_vibrancy.opacity Opacity of Vibrancy Effect.  value must be: -1 ~ 0 and not 0 ~ 1

### Environment

```markdown
- OS:
- VSCode:
- Extension:
[Bug]:  Fix WIki vscode_vibrancy.opacity Opacity of Vibrancy Effect.  value must be: -1 ~ 0 and not 0 ~ 1
```

### Anything else?

[Bug]:  Fix WIki vscode_vibrancy.opacity Opacity of Vibrancy Effect.  value must be: -1 ~ 0 and not 0 ~ 1

**Comment by illixion** [comment]
This is wrong, correct values are 0.0 to 1.0.

**Comment by ShayBox** [comment]
This should be put on the text of the setting, I had to find this closed issue to figure out that it's not 0-100 like most transparency/opacity settings.

An even better improvement would be auto range scaling, if the input is > 1 adjust the scale to 0-100
