### ISSUE TITLE
[Bug]: Can't change sidebar color

### ISSUE THREAD

**Issue by Jnorm911** [illixion/vscode-vibrancy-continued#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Doesn't matter the theme, self made or not. The sidebar is always slightly lighter than the editor. Even if I use "sideBar.background": "#ff0000" the sidebar color will not change.
![sidebar color](https://user-images.githubusercontent.com/35921587/219921360-e1c4b306-1ff9-497e-9944-0bfd4c2e24dd.png)

### Expected Behavior

Sidebar should be the same color as the editor on a blank theme.

### Steps To Reproduce

Make/Change theme.

### Environment

```markdown
- OS: Windows 11
- VSCode: Latest
- Extension: Latest Stable
```

**Comment by illixion** [comment]
Vibrancy overrides some of the styling options in VSCode, so you need to instead create a CSS file that has the following code snippet:

```css
.monaco-workbench .part.sidebar {
  background-color: unset !important;
}
```

Afterwards, add the full path to the CSS file as an import in Vibrancy settings. That should remove the tint on the sidebar.
