### ISSUE TITLE
[Bug]: No transparent when open .ipynb file (jupyter notebook in vscode)

### ISSUE THREAD

**Issue by hjnnjh** [illixion/vscode-vibrancy-continued#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just the problem I mentioned in the title, here is a corresponding picture
![image](https://user-images.githubusercontent.com/37699150/222424877-5e8f5dbd-e750-483e-b75a-ab214f72cb83.png)

### Expected Behavior

Apply the transparency effect when open the.ipynb file

### Environment

```markdown
- OS: macOS 13.1
- VSCode: 1.76.0
- Extension: 1.1.12
```

**Comment by illixion** [comment]
Fixed by #79.
