### ISSUE TITLE
[Bug]: Can't reload vibrancy on Mac m1

### ISSUE THREAD

**Issue by eduard-unplugged** [illixion/vscode-vibrancy-continued#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Command Reload Vibrancy resulted in a an error : A system error occurred (EACCES: permission denied, mkdir '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6')

### Environment

```markdown
- OS: macOS 12
- VSCode:latest
- Extension:Vibrancy Continued
```

**Comment by illixion** [comment]
Seems like your installation of VSCode is owned by another user, run the following command in the Terminal to take ownership of the files, which should fix this error: `sudo chown -R $(whoami):staff "/Applications/Visual Studio Code.app/"`
