### ISSUE TITLE
[Bug]:  Top topbar is not transparent

### ISSUE THREAD

**Issue by declanchiu** [illixion/vscode-vibrancy-continued#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/55419399/230712431-291e0e1f-c1ce-43b8-9e0e-2a05ac57266c.png">

<img width="692" alt="image" src="https://user-images.githubusercontent.com/55419399/230712464-6b0250e5-db0f-401a-ae76-4f1198a288ba.png">

### Environment

```markdown
- OS: 13.0.1
- VSCode: 1.77.1
- Extension: 1.1.14
```

**Comment by illixion** [comment]
Please ensure that all of your "Window" settings are set to default, there are quite a few settings there that cause VSCode to render the default macOS window controls if changed.

**Comment by declanchiu** [comment]
> Please ensure that all of your "Window" settings are set to default, there are quite a few settings there that cause VSCode to render the default macOS window controls if changed.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/55419399/230743495-1deadfd3-448e-4d4c-a185-930d380a7eec.png">

Thank you very much, I found the reason. The current setting here is "custom"
