### ISSUE TITLE
[Bug]:  Extension doesn't make window transparent

### ISSUE THREAD

**Issue by K1T3K1** [illixion/vscode-vibrancy-continued#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Doesn't work on OS X. Window not transparent
<img width="2951" alt="image" src="https://user-images.githubusercontent.com/89193001/231998907-4112b542-f31f-40ec-a569-1fb0503353dc.png">

### Expected Behavior

Window should become transparent

### Environment

```markdown
- OS: OS X 13.2.1
- VSCode: 1.77.3
- Extension: 1.1.14
    "vscode_vibrancy.opacity": 0.5,
    "vscode_vibrancy.theme":"Default Dark",
    "vscode_vibrancy.refreshInterval": 1,
    "workbench.colorTheme": "Default Dark+"
```

**Comment by illixion** [comment]
Hi, could you please check the following:

- "Enable Vibrancy" was used after installing the extension
- VSCode was restarted after using above action
- Dark+ is your current theme
- None of the VSCode "Window" settings were changed from defaults

If you're still experiencing this issue after checking all of the above, use the "Toggle Developer Tools" action and check if there are any errors in the Console section.

**Comment by K1T3K1** [comment]
I enabled vibrancy and restarted vscode several times, after enabling I used >Reload Vibrancy. Dark+ is my current theme. I had window.titleBarStyle: "custom". Changed it to native, didn't help. In developer tools I see only error from OracleSQL extension
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/89193001/232406479-07d27f5e-6346-4eca-b163-46b1d5088bc9.png">

**Comment by circles-png** [comment]
can confirm – `code -v` returns
```
1.78.0-insider
95396f14dbae4d5def754d8635010f8e5743f56c
arm64
```

**Comment by illixion** [comment]
@K1T3K1 just noticed that you're also using `vscode-custom-css` which might be conflicting with Vibrancy, could you please try disabling it (as well as other UI extensions perhaps) and checking if that fixes it?

**Comment by illixion** [comment]
Verified that everything works properly on both stable and insider versions of VSCode, closing as stale since I haven't received a response. Try reinstalling VSCode and reopening this issue if you can reproduce it without any additional extensions or configuration changes.
