### ISSUE TITLE
[Bug]: Terminal not supporting transparency

### ISSUE THREAD

**Issue by jain-arihant-2002** [illixion/vscode-vibrancy-continued#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/91581141/233602387-5e2dbea8-b8e7-4243-a84b-72f3cdb15fc9.png)

### Expected Behavior

Expected Behavior is having a transparent look in terminal also like code space.

### Environment

```markdown
- OS: Windows 11
- VSCode:1.77.3
- Extension: 1.1.14
```

**Comment by illixion** [comment]
Have you tried the solution mentioned in the [FAQ](https://github.com/illixion/vscode-vibrancy-continued#effect-doesnt-work-for-terminal)?

> ## Effect doesn't work for terminal?
> Check your settings. You should change the renderer type of the terminal to dom.
>
> `"terminal.integrated.gpuAcceleration": "off"`

**Comment by jain-arihant-2002** [comment]
It worked thanks and my bad 😢
