### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bu-okem** [illixion/vscode-vibrancy-continued#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On reload vibrancy, a prompt comes up saying "A system error occurred (EROFS: read-only file system, mkdir '/private/var/folders/b9/kj2_23gs0tndj6c9dzm9gh8r0000gp/T/AppTranslocation/47CBE39B-9C57-4154-9260-B85F7451D041/d/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6')"

### Environment

```markdown
- OS:
- VSCode:
- Extension:
- Theme:
```

**Comment by illixion** [comment]
Duplicate, please refer to https://github.com/illixion/vscode-vibrancy-continued/issues/30 for the solution.
