### ISSUE TITLE
[Bug]: The blur color on windows11 is abnormal and distort.

### ISSUE THREAD

**Issue by ShqWW** [illixion/vscode-vibrancy-continued#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The color of the blur is abnormal.

When the real background color is white, the vscode blur is dark, just as the scerrenshot below, and other colors like red are also abnormal and distort. I'm not sure it is a bug or just a feature. I hope it can show the real color in the vscode blur.
![屏幕截图 2023-07-08 162357](https://github.com/illixion/vscode-vibrancy-continued/assets/46523891/47038193-90b8-4ea6-a2ee-31fa05bc6759)

### Environment

```markdown
- OS:  Windows11 22H2
- VSCode: 1.80.0
- Extension: vibrancy-continued 1.1.20
- Theme: Dark+
```

**Comment by illixion** [comment]
Known issue, tracked under #46. You could try lowering the opacity level in Vibrancy settings as a workaround, but the incorrect colors will remain unfortunately.
