### ISSUE TITLE
[Bug]: Your Code installation appears to be corrupt. Please reinstall.

### ISSUE THREAD

**Issue by SohelIslamImran** [illixion/vscode-vibrancy-continued#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open VS code I get this warning with this link : https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported
Your Code installation appears to be corrupt. Please reinstall.
<img width="576" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/76745339/7b239434-1019-4005-9635-54b96895b44f">

### Environment

```markdown
- OS: MacOS
- VSCode:Latest
- Extension:
- Theme:
```

**Comment by illixion** [comment]
Please check the extension’s description, this is expected behavior.
