### ISSUE TITLE
[Bug]: Breaks blur filter in css.

### ISSUE THREAD

**Issue by RoyalFoxy** [illixion/vscode-vibrancy-continued#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using custom imported css files or the dev tools to apply a blur filter to a div with a transparant background like a popup the background just stays transparant and doesn't get blurred

### Expected Behavior

The background should be blurred and not just transparanent when applying a blur filter

### Steps To Reproduce

open dev tools and add a backdrop-filter blur on some element which has a transparant background

### Environment

```markdown
- OS: MacOS 14.0
- VSCode: 1.81.0
- Extension: Vibrancy continued
- Theme: Dark+
```

**Comment by illixion** [comment]
Ensure that you're adding `!important` to your CSS statements, Vibrancy uses it to override the default VSCode theme, and without that your custom CSS will also be overridden.

**Comment by RoyalFoxy** [comment]
Not the color is the problem, setting the background works fine but the problem is that the backdrop-filter set to blur(10px) doesn't seem to work. The text just seems to stay ontop of it even after setting the z-index. However it's only "ontop" if the background has a certain transparancy

<img width="1800" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/48829979/caea0386-9bd8-49b8-b99d-d1766684f77f">

**Comment by illixion** [comment]
I've looked into it, seems to be a known issue: https://github.com/electron/electron/issues/19765#issuecomment-1251686375

Not much that we can do it seems like, but you could try using a semi-opaque dark background instead.
