### ISSUE TITLE
[Feature]: Allow changed workbench.html

### ISSUE THREAD

**Issue by RoyalFoxy** [illixion/vscode-vibrancy-continued#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm always frustrated when I have to reload vibrancy continued and the workbench.html file isn't the original.

### Describe your idea or feature request

My other extensions that add animations to vscode or other ui related things that also edit the workbench.html file conflict with vibrancy and won't allow it to reload or disable... This clearly isn't needed as other extensions work fine without needing the workbench.html file to be the original file and I don't see why this is needed for vibrancy continued. It would be a huge improvement imo and would open up the door for more complex customizations like having animations and vibrancy etc.

**Comment by illixion** [comment]
Vibrancy doesn't really care about the contents of the workbench file, the only important part is for the CSP `<meta>` tag to still be present. Some extensions completely remove it, which means that Vibrancy and other custom extensions like it will no longer be able to load custom JavaScript into the editor window, and that might also break other functionality that depends on the CSP tag. Ensure that your other extensions are preserving the `<meta>` tag.

**Comment by RoyalFoxy** [comment]
A quick question from my side then, why would anyone want to remove this csp tag? I checked and custom css loader seems to remove this tag but I wonder if vibrancy could achieve loading custom css without removing the csp tag why does this extension remove it?

**Comment by illixion** [comment]
I don’t really know, but I’d assume that they just overwrite the workbench file in its entirety and may have forgotten to add the CSP tag. It only affects JavaScript loading, which may not be needed by them, but is required for Vibrancy to load the necessary supporting JS scripts. There might be a way to add it ourselves, but I’d rather not mess with externally modified files in case that breaks something else.

**Comment by RoyalFoxy** [comment]
Well I saw that they added a script tag in addition to removing the csp tag. Ill open an issue on their github page and look further. Thanks for the help!
