### ISSUE TITLE
[Bug]: VS Code needs reinstall after installing the theme

### ISSUE THREAD

**Issue by VSYPER** [illixion/vscode-vibrancy-continued#91]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I'm installing the extension and enable it. I tried all ways but VS Code shows a notification and says I have to reinstall the VS Code to fix corrupted files.

### Expected Behavior

My VS Code is working with glass effect

### Steps To Reproduce

1. Installing the extension
2. Restarting VS Code
3. Nothing changed, so click ctrl + shift + p then type enable Vibrancy
4. Restart VS Code to set it enabled
5. It does not work sometimes and it works sometimes but same notification that says reinstall VS Code to fix corrupted files.
---
1. Installing the extension
2. It asks to install the extension on the bottom of the right side, click install
3. it requires restarting the VS Code, restart the VS Code
4. It does not work sometimes and it works sometimes but same notification that says reinstall VS Code to fix corrupted files.

### Environment

```markdown
- OS: Microsoft Windows 11 Pro | 10.0.22621 N/A Build 22621
- VSCode: 1.81.1
- Extension: Vibrancy-Continued
- Theme: Vibrancy
```

**Comment by VSYPER** [comment]
Is this breaking something on VS Code? If It says it without any real corruption, I'll try to use the extension/theme. But It does not work sometimes.

**Comment by illixion** [comment]
Please check the extension's description, this is intended behavior. Also, would you mind clarifying what doesn't work exactly? Does the VSCode window just not have transparency sometimes, or is there something that's causing it?

**Comment by VSYPER** [comment]
After I enable the theme, sometimes VSCode windows not have transparency. Also, Is something being corrupted really or the notification is fully false?

**Comment by illixion** [comment]
> After I enable the theme, sometimes VSCode windows not have transparency.

Is there anything that changes in your environment or with the computer at all when transparency stops working? For example, if you're on a laptop, entering power saver mode could disable transparency effects globally. You can also try checking the Console section of VSCode's Developer Tools in case there are any errors, this can be done by using Help → Toggle Developer Tools.

> Also, Is something being corrupted really or the notification is fully false?

Vibrancy modifies a few VSCode application files to inject the necessary JavaScript and CSS files, which VSCode considers as corruption and reports it as such. All changes can be reverted through the extension though, and you can read the source code [here](https://github.com/illixion/vscode-vibrancy-continued/blob/master/extension/index.js#L222) if you want to know exactly what's being added.

**Comment by VSYPER** [comment]
Like now
https://prnt.sc/uFbIbhNIeaJ-
I enabled it but there is no transparency effect, I reloaded everything. 
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/142699606/670a41d3-f44d-4ae8-9911-87e9eb7ad685)

**Comment by VSYPER** [comment]
Also there is something like this in settings
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/142699606/f1a6886e-9afb-4382-8902-a6d4b76c1226)

**Comment by illixion** [comment]
> Like now
> https://prnt.sc/uFbIbhNIeaJ-

Yeah, looks like something is disabling transparency effects globally. There is a Windows setting that controls that, perhaps something on your machine is updating it without your knowledge? Try this FAQ entry and see if that fixes it: https://github.com/illixion/vscode-vibrancy-continued#effect-doesnt-work-but-there-arent-any-errors

**Comment by VSYPER** [comment]
Transparent effect was globally disabled on my system idk why, I enabled it then I had to restart my computer to enable it globally. It's instantly enabling transparency but VSCode does not detect it, I had to restart and now It's working fine! Thanks a lot

**Comment by illixion** [comment]
No problem, glad to hear that it works for you now
