### ISSUE TITLE
[Bug]: Minimize/ Max/ Close button in the title bar doesn't get the vibrancy effect

### ISSUE THREAD

**Issue by beetrandahiya** [illixion/vscode-vibrancy-continued#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/illixion/vscode-vibrancy-continued/assets/63427355/f91dcd25-cec6-48a6-8686-c756997c902e)

The minimize/ Max/ Close button in the title bar doesn't get the vibrancy effect, giving i a weird look over such beautiful theme.

### Expected Behavior

The buttons should show vibrancy effect

### Environment

```markdown
- OS: Windows 11
- VSCode: 1.81.1
- Extension: 1.1.20
- Theme: auto
```

### Anything else?

![image](https://github.com/illixion/vscode-vibrancy-continued/assets/63427355/d01b679b-cd0b-47fc-a839-dff5fa87366e)

**Comment by illixion** [comment]
This issue is caused by "Native Window Controls" VSCode setting being enabled by default, the extension is supposed to turn if off automatically, but it seems like it sometimes fails to do so. Will need to investigate that further.

**Comment by beetrandahiya** [comment]
I can find such a setting 
although i found these, and turned them both to custom, but nothing changed
![image](https://github.com/illixion/vscode-vibrancy-continued/assets/63427355/25848e88-c86b-4ffd-b143-d80dc24849eb)

**Comment by illixion** [comment]
You're right, the setting was renamed at some point, it's now called "Window Controls Overlay"

**Comment by whr3430633** [comment]
> You're right, the setting was renamed at some point, it's now called "Window Controls Overlay"

There is no setting named "Window Controls Overlay" in my case... 😢
Windows 11 23H2 22631.2861
Vscode Version: 1.85.1

**Comment by illixion** [comment]
@whr3430633 please see https://github.com/illixion/vscode-vibrancy-continued/issues/49 for info on why it’s missing

**Comment by whr3430633** [comment]
> @whr3430633 please see #49 for info on why it’s missing

got it, thanks 👍
