### ISSUE TITLE
[Bug]: not working on vsc 1.82.2

### ISSUE THREAD

**Issue by SalvoRusso8** [illixion/vscode-vibrancy-continued#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed for the first time the extension on my VSC, but even following the instructions, reloading Vibrancy e restarting VSC, the extension is not working, and no specific error is shown.

### Expected Behavior

To apply the transparent effect after installation

### Environment

```markdown
- OS: MacOS 13.5.2 (22G91)
- VSCode: Version: 1.82.2 Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
- Extension: v1.1.21
- Theme: all
```

### Anything else?

settings.json

<img width="499" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/61883800/73df1f46-8e93-46b4-b265-7cc1bef85e7a">

**Comment by illixion** [comment]
Your opacity is set to `1`, meaning there won’t be any transparency, set it to `-1` and try again.

**Comment by SalvoRusso8** [comment]
> Your opacity is set to `1`, meaning there won’t be any transparency, set it to `-1` and try again.

Hi, I tried but nothing changes, even changing many "vscode_vibrancy.type"

<img width="1287" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/61883800/15fbc62f-08f2-490e-9cda-060f47667642">

**Comment by illixion** [comment]
Type can only be `acrylic` on Windows, please check this section of the description to understand the options: https://github.com/illixion/vscode-vibrancy-continued?tab=readme-ov-file#options

Also, have you tried following this FAQ answer for your question? https://github.com/illixion/vscode-vibrancy-continued?tab=readme-ov-file#effect-doesnt-work-but-there-arent-any-errors

**Comment by SalvoRusso8** [comment]
> Type can only be acrylic on Windows, please check this section of the description to understand the options: https://github.com/illixion/vscode-vibrancy-continued?tab=readme-ov-file#options

Yes I noted it before sending my last comment, but also usin `auto` or something different like `appearance-based` in the screenshot, nothing changes

> Also, have you tried following this FAQ answer for your question? https://github.com/illixion/vscode-vibrancy-continued?tab=readme-ov-file#effect-doesnt-work-but-there-arent-any-errors

Yes, transparency is working in all other applications that have it like outlook for example, so I don't think is OS related. In the console I have an error but I don't know if it is related to Vibrancy
<img width="980" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/61883800/664a4957-0276-432f-bfdf-2ee45f429eaa">

Please ask anything that can be useful to understand if I am doing something wrong. And thank you for your help

**Comment by illixion** [comment]
Hmm, was your earlier screenshot of the main window taken after enabling Vibrancy? The theme should at least look different from standard Dark+ with Vibrancy active. Can you try running these terminal commands and posting the output here?

```sh
ls "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v6"
grep -q "trusted-types VscodeVibrancy" "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html"; echo $?
grep -q "VSCODE-VIBRANCY-START" "/Applications/Visual Studio Code.app/Contents/Resources/app/out/main.js"; echo $?
```

**Comment by SalvoRusso8** [comment]
> Hmm, was your earlier screenshot of the main window taken after enabling Vibrancy?

Yes, after enabling and reloading Vibrancy more then once

Here are the commands output

<img width="926" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/61883800/112b0ebb-4291-40ec-9c0e-1fd690e0b1aa">
<img width="1186" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/61883800/000c6051-14aa-4ecd-b8a5-d6f4a37ed0b8">
<img width="838" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/61883800/31445ee6-e6a7-4090-a85b-4a4f4f1cdc55">

**Comment by illixion** [comment]
Everything looks correct, so I'm not sure why you're experiencing this. I'll see if I can reproduce this later, but in the meantime, you could try reinstalling your VSCode as that's what worked for a few other people with a similar problem. This may also be caused by other extensions, so you could try disabling all of them through the triple-dot menu in the Extensions sidebar.

**Comment by SalvoRusso8** [comment]
Looks like reinstalling VSCode solved the problem, disabling all the extensions was not enough.
Maybe can be worth to add to the documentation this step, since reinstalling I didn't lose any configuration so it's not a big problem.

Thank you very much

**Comment by illixion** [comment]
You're right, I'll add that, glad to hear it works now!
